### ISSUE TITLE
Why include zlib, lzma, bzip2, tar, zip etc?

### ISSUE THREAD

**Issue by coolaj86** [gen2brain/go-unarr#13]
The reason that I'm using this is for a cross-platform `un7z`, which has not been implemented in a language that can be easily cross-compiled.

Go has builtin natives for:

- [x] [zip](https://golang.org/pkg/archive/zip/)
- [x] [tar](https://golang.org/pkg/archive/tar/)
- [x] [gzip](https://pkg.go.dev/compress/gzip)

And other native Go code for most other formats:
- [x] [github.com/mholt/archiver](https://github.com/mholt/archiver) (`brotli`, `snappy`, `xz`, `rar` etc)
    - [x] [bzip2](https://github.com/dsnet/compress/bzip2)
    - [x] [rardecode](https://github.com/nwaples/rardecode)
    - [x] [pgzip](github.com/klauspost/pgzip)
    - [x] [brotli](github.com/andybalholm/brotli)
    - ...
- [x] [webinstall.dev/arc](https://webinstall.dev/arc) (installer for archiver ^^)

Is there are reason that all of these already-go-native formats are included in this project?

**Comment by gen2brain** [comment]
Well, yes, this is a wrapper for `unarr` library, that supports all those formats. In order to remove support, the code must be changed to work without those libs, if it would be enough to not include some files something can be done with tags, i.e. nozlib etc.
But how it is, it would need a lot of work just to remove a few KB. If one doesn't want to use it for zip or tar, then just don't use it and use native libs instead :) I think it is also nice to have an alternative in C, so it can be compared. Also, usually native Go libs are a lot slower (i.e. libjpeg-turbo vs image/jpeg is 5x faster).

**Comment by coolaj86** [comment]
Makes perfect sense. Thanks.
